security:
    encoders:
        CheckTimer\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        main:
            entity:
                class:    CheckTimer\UserBundle\Entity\User
                property: username

    firewalls:
        secured_area:
            pattern:   ^/
            anonymous: ~

            form_login:
                check_path: /user/login_check
                login_path: /user/login
            logout:
                path:   /user/logout
                target: /
